name = "qianfu-lottery-api"
main = "src/index.ts"
compatibility_date = "2024-05-20"
compatibility_flags = ["nodejs_compat"]

# 默认环境变量
vars = { ENVIRONMENT = "production" }

# 启用 Workers Logs
[observability]
enabled = true

# 环境变量需要在 Cloudflare Dashboard 中设置:
# - DATABASE_URL: Neon 数据库连接字符串
# - JWT_SECRET: JWT 签名密钥